name: Scheduled E2E Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 10 * * *'

jobs:
  run_e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn and dependencies
        run: |
          corepack enable
          yarn set version 3.2.1
          yarn install

      - name: Playwright install
        run: node_modules/.bin/playwright install --with-deps

      - name: Run tests for all plans
        env:
          TEST_PLAN_IDENTIFIERS: ${{ secrets.TEST_PLAN_IDENTIFIERS }}
          APLANS_API_BASE_URL: 'https://api.watch.kausal.tech/v1'
        run: |
          IFS=',' read -ra PLAN_IDS <<< "${TEST_PLAN_IDENTIFIERS}"
          for PLAN_ID in "${PLAN_IDS[@]}"
          do
            TEST_PAGE_BASE_URL="http://$PLAN_ID.watch.staging.kausal.tech"
            echo "Running tests for plan $PLAN_ID with base URL $TEST_PAGE_BASE_URL"
            TEST_PAGE_BASE_URL=$TEST_PAGE_BASE_URL node_modules/.bin/playwright test
          done

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
