name: CI-e2e-tests
on:
  workflow_dispatch:
    inputs:
      plan_identifiers:
        description: 'Comma separated list of plan identifiers'
        required: true
        default: 'sunnydale'
      frontend_base_url:
        description: 'Base url for environment to run tests against'
        required: true
        default: 'http://{planId}.watch.staging.kausal.tech'
      backend_base_url:
        description: 'Base url for backend API'
        required: true
        default: 'https://api.watch.kausal.tech/v1'

jobs:
  e2e_test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn
        run: |
          corepack enable
          yarn set version 3.2.1
          yarn config set nodeLinker 'node-modules'
          yarn config set npmScopes.kausal/themes-private.npmRegistryServer "$YARN_NPM_REGISTRY_SERVER"
          yarn config set npmScopes.kausal/themes-private.npmAlwaysAuth true
          yarn config set npmScopes.kausal/themes-private.npmAuthToken $YARN_NPM_AUTH_TOKEN
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_IDENT }}
          YARN_NPM_REGISTRY_SERVER: ${{ secrets.NPM_REGISTRY_SERVER }}

      - name: Install dependencies
        continue-on-error: true
        run: yarn install

      - name: Playwright install
        run: npx playwright install --with-deps

      - name: Running Playwright e2e tests
        run: npx playwright test
        env:
          TEST_PLAN_IDENTIFIERS: ${{ github.event.inputs.plan_identifiers }}
          TEST_PAGE_BASE_URL: ${{ github.event.inputs.frontend_base_url }}
          APLANS_API_BASE_URL: ${{ github.event.inputs.backend_base_url }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
