name: E2e-tests
on:
  workflow_dispatch:
    inputs:
      plan_identifiers:
        description: 'Comma separated list of plan identifiers'
        required: true
        default: 'sunnydale'
      frontend_base_url:
        description: 'Base url for environment to run tests against'
        required: true
        default: 'http://{planId}.watch.staging.kausal.tech'
      backend_base_url:
        description: 'Base url for backend API'
        required: true
        default: 'https://api.watch.kausal.tech/v1'

jobs:
  e2e_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        run: |
          corepack enable
          yarn set version 3.2.1
          yarn config set nodeLinker 'node-modules'
          yarn config set npmScopes.kausal.npmRegistryServer "${{ secrets.NPM_REGISTRY_SERVER }}"
          yarn config set npmScopes.kausal.npmAlwaysAuth true
          yarn config set npmScopes.kausal.npmAuthIdent ${{ secrets.NPM_AUTH_IDENT }}

      - name: Install dependencies
        run: yarn install

      - name: Playwright install
        run: node_modules/.bin/playwright install

      - name: Install WebKit dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libwoff2dec1 \
          libvpx7 \
          libevent-2.1-7 \
          libopus0 \
          libharfbuzz-icu0 \
          libgstallocators-1.0-0 \
          libgstapp-1.0-0 \
          libgstpbutils-1.0-0 \
          libgstaudio-1.0-0 \
          libgsttag-1.0-0 \
          libgstvideo-1.0-0 \
          libgstgl-1.0-0 \
          libgstcodecparsers-1.0-0 \
          libgstfft-1.0-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libfliteusenglish1 \
          libflitecmugraphemelang1 \
          libflitecmugraphemelex1 \
          libflitecmuindiclang1 \
          libflitecmuindiclex1 \
          libflitecmulex1 \
          libflitecmutimeawb1 \
          libflitecmuusawb1 \
          libflitecmuuskal161 \
          libflitecmuuskal1 \
          libflitecmuusrms1 \
          libflitecmuusslt1 \
          libgles2 \
          libx264-dev

      - name: Running Playwright e2e tests
        run: node_modules/.bin/playwright test
        env:
          TEST_PLAN_IDENTIFIERS: ${{ github.event.inputs.plan_identifiers }}
          TEST_PAGE_BASE_URL: ${{ github.event.inputs.frontend_base_url }}
          APLANS_API_BASE_URL: ${{ github.event.inputs.backend_base_url }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
