name: CI
on: push
jobs:
  build_test_and_push:
    name: Build Docker images, run tests and push to Docker registry
    runs-on: ubuntu-latest
    env:
      BUILDKIT_PROGRESS: plain
      DOCKER_IMAGE: docker.kausal.tech/watch-ui
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Building Docker base container
        run: |
          docker build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --load \
            --tag kausal-watch-ui/base \
            --target base .
      - name: Running Jest unit tests
        run: docker run --rm --entrypoint '' kausal-watch-ui/base yarn test
      - name: Building NextJS bundles
        run: |
          docker build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.not-cached" \
            --tag ${{ env.DOCKER_IMAGE }} \
            --load \
            .
      - name: Log into Docker registry
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/deployment/staging'
        uses: docker/login-action@v1
        with:
          registry: docker.kausal.tech
          username: docker
          # FIXME: Instead of using the password, we should probably switch to token authentication with limited scope
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push latest tag to Docker registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:latest
      - name: Add staging tag and push to registry
        if: github.ref == 'refs/heads/deployment/staging'
        run: |
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:staging-${{ github.run_number }}
          docker push ${{ env.DOCKER_IMAGE }}:staging-${{ github.run_number }}
