name: CI
on: push
jobs:
  build_test_and_push:
    name: Build Docker images, run tests and push to Docker registry
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: docker.kausal.tech/watch-ui
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Building Docker base container
        run: |
          docker build \
            --tag kausal-watch-ui/base \
            --target base .
      - name: Running Jest unit tests
        run: docker run --rm --entrypoint '' kausal-watch-ui/base yarn test
      - name: Building NextJS bundles
        run: |
          docker build \
            --tag ${{ env.DOCKER_IMAGE }} \
            .
      - name: Log into Docker registry
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/deployment/staging'
        uses: docker/login-action@v1
        with:
          registry: docker.kausal.tech
          username: docker
          # FIXME: Instead of using the password, we should probably switch to token authentication with limited scope
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push latest tag to Docker registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:latest
      - name: Add staging tag and push to registry
        if: github.ref == 'refs/heads/deployment/staging'
        run: |
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:staging-${{ github.run_number }}
          docker push ${{ env.DOCKER_IMAGE }}:staging-${{ github.run_number }}
