name: CI
on: push
jobs:
  build_and_test:
    name: Build Docker container and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Building Docker base container
        run: docker buildx build --target base -t kausal-watch-ui/base .
      - name: Running Jest unit tests
        run: docker run kausal-watch-ui/base --entrypoint '' yarn test
      - name: Building NextJS bundles
        run: docker buildx build .
