name: CI
on: push

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      project_name: watch-ui
      docker_image_name: watch-ui
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
    secrets: inherit
