name: CI
on: push

jobs:
  build:
    uses: kausaldev/github-actions/.github/workflows/build-nextjs.yaml@main
    with:
      project_id: watch-ui
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/e2e-image.yaml
    with:
      image: ${{ needs.build.outputs.image }}:${{ needs.build.outputs.image_tag }}
      plan_identifiers: sunnydale
      backend_base_url: https://api.watch.kausal.tech/v1
      build_id: ${{ needs.build.outputs.build_id }}
      s3_endpoint: ${{ vars.BUILD_S3_ENDPOINT }}
      s3_bucket: ${{ vars.BUILD_S3_BUCKET }}
    secrets: inherit

  deploy:
    needs: [build]
    uses: kausaldev/github-actions/.github/workflows/deploy.yaml@main
    secrets: inherit
    if: needs.build.outputs.deployment_env
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      project_id: watch-ui
      deployment_env: ${{ needs.build.outputs.deployment_env }}
