name: CI
on: push

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/e2e-image.yaml
    with:
      image: ${{ needs.build.outputs.image }}:${{ needs.build.outputs.image_tag }}
      plan_identifiers: sunnydale
      backend_base_url: https://api.watch.kausal.tech/v1
      build_id: ${{ needs.build.outputs.build_id }}
      s3_endpoint: ${{ vars.BUILD_S3_ENDPOINT }}
      s3_bucket: ${{ vars.BUILD_S3_BUCKET }}
    secrets: inherit
