name: End-to-end tests
on:
  workflow_call:
    inputs:
      plan_identifiers:
        description: 'Comma separated list of plan identifiers'
        required: true
        type: string
        default: 'sunnydale'
      image:
        description: 'Image (incl. repo, path, tag) to test'
        required: true
        type: string
      backend_base_url:
        description: 'Base URL for backend API'
        required: true
        type: string
        default: 'https://api.watch.kausal.tech/v1'
      build_id:
        description: 'Unique ID for the build'
        required: true
        type: string
      s3_endpoint:
        description: 'S3 endpoint URL where to upload test artifacts'
        required: false
        type: string
      # s3_path_prefix:
      #   description: 'S3 path prefix'
      #   required: false
      #   type: string
      s3_bucket:
        description: 'S3 bucket'
        required: false
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

    outputs:
      test_report_url:
        description: 'URL to e2e test report'
        value: ${{ jobs.e2e_test.outputs.test_report_url }}

jobs:
  e2e_test:
    name: Run tests
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/playwright:v1.43.1
    env:
      TEST_PLAN_IDENTIFIERS: ${{ inputs.plan_identifiers }}
      NEXT_PUBLIC_API_URL: ${{ inputs.backend_base_url }}
      TEST_PAGE_BASE_URL: 'http://{planId}.localhost:3000'
      CI: 1
    services:
      app:
        image: ${{ inputs.image }}
        env:
          NEXT_PUBLIC_WILDCARD_DOMAINS: localhost
          NEXT_PUBLIC_API_URL: https://api.watch.kausal.tech/v1
          NEXT_PUBLIC_DEPLOYMENT_TYPE: testing
          NEXTJS_ASSET_PREFIX: http://localhost:3001
          NEXTJS_PORT: 3000
          CADDY_PORT: 3001
          AUTH_SECRET: abcd
          AUTH_TRUST_HOST: true
          HOSTNAME: 0.0.0.0
    outputs:
      test_report_url: ${{ steps.upload.outputs.test_report_url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./e2e-tests

      - name: Playwright install
        run: node_modules/.bin/playwright install
        working-directory: ./e2e-tests

      - name: Running Playwright e2e tests
        run: node_modules/.bin/playwright test
        working-directory: ./e2e-tests

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: e2e-tests/playwright-report/
      #     retention-days: 5

      - name: Upload test report to S3
        id: upload
        if: always()
        run: |
          apt update && apt install --no-install-recommends -y s3cmd
          s3cmd --host ${{ inputs.s3_endpoint }} --host-bucket ${{ inputs.s3_endpoint }} put --recursive playwright-report s3://${{ inputs.s3_bucket }}/${{ inputs.build_id }}/
          export TEST_REPORT_URL="https://${{ inputs.s3_endpoint }}/${{ inputs.s3_bucket }}/${{ inputs.build_id }}/playwright-report/index.html"
          echo "test_report_url=${TEST_REPORT_URL}" >> $GITHUB_OUTPUT
          echo "✅ End-to-end tests succeeded. 🔗 [Test report](${TEST_REPORT_URL})" >> $GITHUB_STEP_SUMMARY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEBIAN_FRONTEND: noninteractive
        working-directory: ./e2e-tests
